name: CI pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
        mpi: ["mpich", "openmpi"]

    steps:

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install requirements 
      run: bash scripts/install_requirements.sh core tests

    - name: Run serial tests
      run: pytest -v --cov --cov-report xml --cov-append ggce/_tests/*.py

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Install mpi4py and pytest-mpi
      run: pip install mpi4py pytest-mpi

    - name: Run MPI tests
      run: mpiexec -n 2 pytest -v --cov --cov-report xml --cov-append --with-mpi ggce/_tests/mpi/*.py

    - name: Setup PETSc
      run: pip install petsc petsc4py
      env:
        PETSC_CONFIGURE_OPTIONS: "--with-scalar-type=complex --download-mumps --download-scalapack"

    - name: Run PETSc tests
      run: mpiexec -n 4 pytest -v --cov --cov-report xml --cov-append --with-mpi ggce/_tests/petsc/*.py

    - name: Upload code coverage
      uses: codecov/codecov-action@v2
      timeout-minutes: 10
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
